security:

    providers:
        administrators:
            entity: { class: LaPoizWindBundle:User, property: username }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        LaPoiz\WindBundle\Entity\User: plaintext

    firewalls:
        secured_area:
            pattern:    ^/ 
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /index

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }