security:

    providers:
        in_memory:
             memory:
                users:
                    admin: { password: liberte, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        secured_area:
            pattern:    ^/ 
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /index

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }